export const countryList = [
    {
        name: "Afghanistan",
        code: "AF",
        phoneCode: "+93",
        flagEmoji: "🇦🇫",
        flag: "https://flagcdn.com/h40/af.png",
    },
    {
        name: "Argentina",
        code: "AR",
        phoneCode: "+54",
        flagEmoji: "🇦🇷",
        flag: "https://flagcdn.com/h40/ar.png",
    },
    {
        name: "Australia",
        code: "AU",
        phoneCode: "+61",
        flagEmoji: "🇦🇺",
        flag: "https://flagcdn.com/h40/au.png",
    },
    {
        name: "Bangladesh",
        code: "BD",
        phoneCode: "+880",
        flagEmoji: "🇧🇩",
        flag: "https://flagcdn.com/h40/bd.png",
    },
    {
        name: "Brazil",
        code: "BR",
        phoneCode: "+55",
        flagEmoji: "🇧🇷",
        flag: "https://flagcdn.com/h40/br.png",
    },
    {
        name: "Canada",
        code: "CA",
        phoneCode: "+1",
        flagEmoji: "🇨🇦",
        flag: "https://flagcdn.com/h40/ca.png",
    },
    {
        name: "China",
        code: "CN",
        phoneCode: "+86",
        flagEmoji: "🇨🇳",
        flag: "https://flagcdn.com/h40/cn.png",
    },
    {
        name: "Colombia",
        code: "CO",
        phoneCode: "+57",
        flagEmoji: "🇨🇴",
        flag: "https://flagcdn.com/h40/co.png",
    },
    {
        name: "Denmark",
        code: "DK",
        phoneCode: "+45",
        flagEmoji: "🇩🇰",
        flag: "https://flagcdn.com/h40/dk.png",
    },
    {
        name: "Egypt",
        code: "EG",
        phoneCode: "+20",
        flagEmoji: "🇪🇬",
        flag: "https://flagcdn.com/h40/eg.png",
    },
    {
        name: "Ethiopia",
        code: "ET",
        phoneCode: "+251",
        flagEmoji: "🇪🇹",
        flag: "https://flagcdn.com/h40/et.png",
    },
    {
        name: "France",
        code: "FR",
        phoneCode: "+33",
        flagEmoji: "🇫🇷",
        flag: "https://flagcdn.com/h40/fr.png",
    },
    {
        name: "Germany",
        code: "DE",
        phoneCode: "+49",
        flagEmoji: "🇩🇪",
        flag: "https://flagcdn.com/h40/de.png",
    },
    {
        name: "Greece",
        code: "GR",
        phoneCode: "+30",
        flagEmoji: "🇬🇷",
        flag: "https://flagcdn.com/h40/gr.png",
    },
    {
        name: "India",
        code: "IN",
        phoneCode: "+91",
        flagEmoji: "🇮🇳",
        flag: "https://flagcdn.com/h40/in.png",
    },
    {
        name: "Indonesia",
        code: "ID",
        phoneCode: "+62",
        flagEmoji: "🇮🇩",
        flag: "https://flagcdn.com/h40/id.png",
    },
    {
        name: "Iran",
        code: "IR",
        phoneCode: "+98",
        flagEmoji: "🇮🇷",
        flag: "https://flagcdn.com/h40/ir.png",
    },
    {
        name: "Iraq",
        code: "IQ",
        phoneCode: "+964",
        flagEmoji: "🇮🇶",
        flag: "https://flagcdn.com/h40/iq.png",
    },
    {
        name: "Italy",
        code: "IT",
        phoneCode: "+39",
        flagEmoji: "🇮🇹",
        flag: "https://flagcdn.com/h40/it.png",
    },
    {
        name: "Japan",
        code: "JP",
        phoneCode: "+81",
        flagEmoji: "🇯🇵",
        flag: "https://flagcdn.com/h40/jp.png",
    },
    {
        name: "Kenya",
        code: "KE",
        phoneCode: "+254",
        flagEmoji: "🇰🇪",
        flag: "https://flagcdn.com/h40/ke.png",
    },
    {
        name: "Malaysia",
        code: "MY",
        phoneCode: "+60",
        flagEmoji: "🇲🇾",
        flag: "https://flagcdn.com/h40/my.png",
    },
    {
        name: "Mexico",
        code: "MX",
        phoneCode: "+52",
        flagEmoji: "🇲🇽",
        flag: "https://flagcdn.com/h40/mx.png",
    },
    {
        name: "Morocco",
        code: "MA",
        phoneCode: "+212",
        flagEmoji: "🇲🇦",
        flag: "https://flagcdn.com/h40/ma.png",
    },
    {
        name: "Nepal",
        code: "NP",
        phoneCode: "+977",
        flagEmoji: "🇳🇵",
        flag: "https://flagcdn.com/h40/np.png",
    },
    {
        name: "Netherlands",
        code: "NL",
        phoneCode: "+31",
        flagEmoji: "🇳🇱",
        flag: "https://flagcdn.com/h40/nl.png",
    },
    {
        name: "New Zealand",
        code: "NZ",
        phoneCode: "+64",
        flagEmoji: "🇳🇿",
        flag: "https://flagcdn.com/h40/nz.png",
    },
    {
        name: "Nigeria",
        code: "NG",
        phoneCode: "+234",
        flagEmoji: "🇳🇬",
        flag: "https://flagcdn.com/h40/ng.png",
    },
    {
        name: "Norway",
        code: "NO",
        phoneCode: "+47",
        flagEmoji: "🇳🇴",
        flag: "https://flagcdn.com/h40/no.png",
    },
    {
        name: "Pakistan",
        code: "PK",
        phoneCode: "+92",
        flagEmoji: "🇵🇰",
        flag: "https://flagcdn.com/h40/pk.png",
    },
    {
        name: "Peru",
        code: "PE",
        phoneCode: "+51",
        flagEmoji: "🇵🇪",
        flag: "https://flagcdn.com/h40/pe.png",
    },
    {
        name: "Philippines",
        code: "PH",
        phoneCode: "+63",
        flagEmoji: "🇵🇭",
        flag: "https://flagcdn.com/h40/ph.png",
    },
    {
        name: "Poland",
        code: "PL",
        phoneCode: "+48",
        flagEmoji: "🇵🇱",
        flag: "https://flagcdn.com/h40/pl.png",
    },
    {
        name: "Portugal",
        code: "PT",
        phoneCode: "+351",
        flagEmoji: "🇵🇹",
        flag: "https://flagcdn.com/h40/pt.png",
    },
    {
        name: "Qatar",
        code: "QA",
        phoneCode: "+974",
        flagEmoji: "🇶🇦",
        flag: "https://flagcdn.com/h40/qa.png",
    },
    {
        name: "Russia",
        code: "RU",
        phoneCode: "+7",
        flagEmoji: "🇷🇺",
        flag: "https://flagcdn.com/h40/ru.png",
    },
    {
        name: "Saudi Arabia",
        code: "SA",
        phoneCode: "+966",
        flagEmoji: "🇸🇦",
        flag: "https://flagcdn.com/h40/sa.png",
    },
    {
        name: "Singapore",
        code: "SG",
        phoneCode: "+65",
        flagEmoji: "🇸🇬",
        flag: "https://flagcdn.com/h40/sg.png",
    },
    {
        name: "South Africa",
        code: "ZA",
        phoneCode: "+27",
        flagEmoji: "🇿🇦",
        flag: "https://flagcdn.com/h40/za.png",
    },
    {
        name: "South Korea",
        code: "KR",
        phoneCode: "+82",
        flagEmoji: "🇰🇷",
        flag: "https://flagcdn.com/h40/kr.png",
    },
    {
        name: "Spain",
        code: "ES",
        phoneCode: "+34",
        flagEmoji: "🇪🇸",
        flag: "https://flagcdn.com/h40/es.png",
    },
    {
        name: "Sri Lanka",
        code: "LK",
        phoneCode: "+94",
        flagEmoji: "🇱🇰",
        flag: "https://flagcdn.com/h40/lk.png",
    },
    {
        name: "Sweden",
        code: "SE",
        phoneCode: "+46",
        flagEmoji: "🇸🇪",
        flag: "https://flagcdn.com/h40/se.png",
    },
    {
        name: "Switzerland",
        code: "CH",
        phoneCode: "+41",
        flagEmoji: "🇨🇭",
        flag: "https://flagcdn.com/h40/ch.png",
    },
    {
        name: "Thailand",
        code: "TH",
        phoneCode: "+66",
        flagEmoji: "🇹🇭",
        flag: "https://flagcdn.com/h40/th.png",
    },
    {
        name: "Turkey",
        code: "TR",
        phoneCode: "+90",
        flagEmoji: "🇹🇷",
        flag: "https://flagcdn.com/h40/tr.png",
    },
    {
        name: "Ukraine",
        code: "UA",
        phoneCode: "+380",
        flagEmoji: "🇺🇦",
        flag: "https://flagcdn.com/h40/ua.png",
    },
    {
        name: "United Arab Emirates",
        code: "AE",
        phoneCode: "+971",
        flagEmoji: "🇦🇪",
        flag: "https://flagcdn.com/h40/ae.png",
    },
    {
        name: "United Kingdom",
        code: "GB",
        phoneCode: "+44",
        flagEmoji: "🇬🇧",
        flag: "https://flagcdn.com/h40/gb.png",
    },
    {
        name: "United States",
        code: "US",
        phoneCode: "+1",
        flagEmoji: "🇺🇸",
        flag: "https://flagcdn.com/h40/us.png",
    },
    {
        name: "Vietnam",
        code: "VN",
        phoneCode: "+84",
        flagEmoji: "🇻🇳",
        flag: "https://flagcdn.com/h40/vn.png",
    },
];
